In [1]:
import numpy as np
import torch
torch.manual_seed(1)
print(torch.__version__)

1.4.0


# base Tenseor

In [2]:
x = torch.Tensor(2,2)
x

tensor([[-1.5007e+01,  4.5803e-41],
        [ 6.6585e-38,  0.0000e+00]])

In [3]:
x.type(), x.size(), x.numel()

('torch.FloatTensor', torch.Size([2, 2]), 4)

In [4]:
x2 = torch.Tensor(4,3,2,1)
x2

tensor([[[[6.5203e-10],
          [4.3445e-05]],

         [[1.2962e+16],
          [1.2849e+31]],

         [[1.8395e+25],
          [6.1963e-04]]],


        [[[2.1955e-04],
          [2.1780e-04]],

         [[6.5912e-10],
          [5.2438e-08]],

         [[1.0860e-05],
          [5.4648e-05]]],


        [[[2.1860e-04],
          [1.7250e-07]],

         [[2.3052e-12],
          [7.1856e+22]],

         [[4.3605e+27],
          [2.5226e-18]]],


        [[[3.0351e+32],
          [2.7946e+20]],

         [[3.1369e+27],
          [7.0800e+31]],

         [[3.1095e-18],
          [1.8590e+34]]]])

In [5]:
x2.size(), x2.type(), x2.numel()

(torch.Size([4, 3, 2, 1]), 'torch.FloatTensor', 24)


# Other methods make to Tensor

In [6]:
torch.zeros(4,4), torch.ones(4,4), torch.eye(4,4),torch.rand(4,4), torch.randn(4,4)

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 0., 0., 0.],
         [0., 1., 0., 0.],
         [0., 0., 1., 0.],
         [0., 0., 0., 1.]]),
 tensor([[0.7576, 0.2793, 0.4031, 0.7347],
         [0.0293, 0.7999, 0.3971, 0.7544],
         [0.5695, 0.4388, 0.6387, 0.5247],
         [0.6826, 0.3051, 0.4635, 0.4550]]),
 tensor([[-0.6970, -1.1608,  0.6995,  0.1991],
         [ 0.8657,  0.2444, -0.6629,  0.8073],
         [ 1.1017, -0.1759, -2.2456, -1.4465],
         [ 0.0612, -0.6177, -0.7981, -0.1316]]))

In [7]:
x3 = torch.arange(0, 3, step=0.3)
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [8]:
x3

tensor([0.0000, 0.3000, 0.6000, 0.9000, 1.2000, 1.5000, 1.8000, 2.1000, 2.4000,
        2.7000])

In [9]:
torch.Tensor([[6,2],[3,4],[5,6]])

tensor([[6., 2.],
        [3., 4.],
        [5., 6.]])

In [10]:
numpy_test = np.array([[5,6],[10,11]])
torch.from_numpy(numpy_test)

tensor([[ 5,  6],
        [10, 11]])


# Use to array function of Python make Tensor 

In [11]:
x4 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]])
x4

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [12]:
x4[0:2,:]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [13]:
x4[1]

tensor([4., 5., 6.])

In [14]:
x4[0,:]

tensor([1., 2., 3.])

In [15]:
x4[0:1,:] = torch.Tensor([62,72,80])
x4

tensor([[62., 72., 80.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.]])

In [16]:
x4[1] = torch.Tensor([200,78, 89])
x4

tensor([[ 62.,  72.,  80.],
        [200.,  78.,  89.],
        [  7.,   8.,   9.]])

In [17]:
x5 = torch.split(x4, split_size_or_sections=1,dim=0)
x5

(tensor([[62., 72., 80.]]),
 tensor([[200.,  78.,  89.]]),
 tensor([[7., 8., 9.]]))

In [18]:
torch.cat(x5, dim=1)

tensor([[ 62.,  72.,  80., 200.,  78.,  89.,   7.,   8.,   9.]])

In [19]:
torch.stack(x5, dim=1)

tensor([[[ 62.,  72.,  80.],
         [200.,  78.,  89.],
         [  7.,   8.,   9.]]])

In [20]:
x6 = torch.randn(3,3)

mask  = torch.ByteTensor([[1,0,0],[1,1,1],[0,1,0]])

out = torch.masked_select(x6, mask)

x6, mask, out

/pytorch/aten/src/ATen/native/LegacyDefinitions.cpp:70: UserWarning: masked_select received a mask with dtype torch.uint8, this behavior is now deprecated,please use a mask with dtype torch.bool instead.


(tensor([[-0.4212, -0.5107, -1.5727],
         [-0.1232,  3.5870, -1.8313],
         [ 1.5987, -1.2770,  0.3255]]),
 tensor([[1, 0, 0],
         [1, 1, 1],
         [0, 1, 0]], dtype=torch.uint8),
 tensor([-0.4212, -0.1232,  3.5870, -1.8313, -1.2770]))


# Reshaping on dimension of Tensor

In [21]:
x7 = torch.zeros(2,2,1)
x7

tensor([[[0.],
         [0.]],

        [[0.],
         [0.]]])

In [22]:
x7.view(2,2)   # 요즘은 reshape

tensor([[0., 0.],
        [0., 0.]])

In [23]:
x7.view(-1) # -1 = Automatic

tensor([0., 0., 0., 0.])

In [24]:
x7.reshape(-1,2)

tensor([[0., 0.],
        [0., 0.]])

In [25]:
x7.reshape(4)

tensor([0., 0., 0., 0.])

In [26]:
x8 = x7.squeeze()    # 모든 1차원이 사라짐
x7, x8

(tensor([[[0.],
          [0.]],
 
         [[0.],
          [0.]]]),
 tensor([[0., 0.],
         [0., 0.]]))

In [27]:
x8.unsqueeze(0), x8.unsqueeze(0).shape     # axis=0의 위치에 차원의 크기가 1인것을 추가. (2, 2) => (1, 2, 2)

(tensor([[[0., 0.],
          [0., 0.]]]),
 torch.Size([1, 2, 2]))


# Calculate

In [28]:
x9 = torch.FloatTensor([[10,20,30],[40,50,60]])
x10 = torch.FloatTensor([[1,2,3],[4,5,6]])
x9, x10

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[1., 2., 3.],
         [4., 5., 6.]]))

In [29]:
x9  + x10, x9.add(x10), torch.add(x9, x10)

(tensor([[11., 22., 33.],
         [44., 55., 66.]]),
 tensor([[11., 22., 33.],
         [44., 55., 66.]]),
 tensor([[11., 22., 33.],
         [44., 55., 66.]]))

In [30]:
x10.sub(x9), x9.sub(x10)

(tensor([[ -9., -18., -27.],
         [-36., -45., -54.]]),
 tensor([[ 9., 18., 27.],
         [36., 45., 54.]]))

In [31]:
x10[1] + 12

tensor([16., 17., 18.])

In [32]:
x9 * x10, x10.mul(x9), torch.mul(x10,x9)  # 사칙연산에서의 곱셈. 행렬곱 아님

(tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]),
 tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]),
 tensor([[ 10.,  40.,  90.],
         [160., 250., 360.]]))

In [33]:
x10 * 10

tensor([[10., 20., 30.],
        [40., 50., 60.]])


# Other Calculate

In [34]:
x9.pow(2), torch.pow(x9,2), x9 ** 2

(tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]),
 tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]),
 tensor([[ 100.,  400.,  900.],
         [1600., 2500., 3600.]]))

In [35]:
x9.sqrt()

tensor([[3.1623, 4.4721, 5.4772],
        [6.3246, 7.0711, 7.7460]])

In [36]:
x10.log(), torch.log(x10)

(tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]),
 tensor([[0.0000, 0.6931, 1.0986],
         [1.3863, 1.6094, 1.7918]]))

In [37]:
x9 % 3, x9 / 3

(tensor([[1., 2., 0.],
         [1., 2., 0.]]),
 tensor([[ 3.3333,  6.6667, 10.0000],
         [13.3333, 16.6667, 20.0000]]))

In [38]:
x9.sum(), x9.max()

(tensor(210.), tensor(60.))

In [39]:
x10.min(), x10.min(0), x10.min(1)

(tensor(1.),
 torch.return_types.min(
 values=tensor([1., 2., 3.]),
 indices=tensor([0, 0, 0])),
 torch.return_types.min(
 values=tensor([1., 4.]),
 indices=tensor([0, 0])))

In [40]:
x10.max(1)

torch.return_types.max(
values=tensor([3., 6.]),
indices=tensor([2, 2]))

In [41]:
x9.abs(), x9

(tensor([[10., 20., 30.],
         [40., 50., 60.]]),
 tensor([[10., 20., 30.],
         [40., 50., 60.]]))

In [42]:
x9[1] = torch.Tensor([-3,3,-10])
x9, x9.abs()

(tensor([[ 10.,  20.,  30.],
         [ -3.,   3., -10.]]),
 tensor([[10., 20., 30.],
         [ 3.,  3., 10.]]))

In [43]:
value, index = x10.max(dim = 1)
value, index

(tensor([3., 6.]), tensor([2, 2]))

In [44]:
x10.max()

tensor(6.)


# Matrix Calculate

In [45]:
x11 = torch.randn(3,5)
x12 = torch.randn(5,5)
x13 = torch.randn(5,3)
x11, x12, x13

(tensor([[-0.4791,  1.3790,  2.5286,  0.4107, -0.9880],
         [-0.9081,  0.5423,  0.1103, -2.2590,  0.6067],
         [-0.1383,  0.8310, -0.2477, -0.8029,  0.2366]]),
 tensor([[-0.5065,  0.0998, -0.6540,  0.7317, -1.4344],
         [-0.5008,  0.1716, -0.1600,  0.2546,  0.1938],
         [-2.5832,  0.8539,  1.2466,  0.5057,  0.9505],
         [ 1.2966,  0.8738,  0.3434, -1.0703, -0.8743],
         [-1.4648, -1.2629,  1.1220,  1.5663,  2.5581]]),
 tensor([[-1.1322, -0.0179,  0.1280],
         [-0.5552, -0.4575, -1.9599],
         [-1.1242, -1.5599,  1.4003],
         [ 0.2963, -1.0901, -0.2380],
         [ 0.6905,  0.4646, -0.7559]]))

In [46]:
1.6200 * 1.1375  + 0.3436 * -0.9347 + -0.9112 * 1.3267 + -0.9952 *  -0.0336 + 0.7455 * 1.3210

1.33094226

In [47]:
torch.mm(x11,x12), x11.mm(x12)    # 행렬곱(dot product)

(tensor([[-4.9999,  3.9548,  2.2772, -0.7079,  0.4714],
         [-3.9143, -2.6435,  0.5496,  2.8975,  5.0394],
         [-1.0939, -1.0831, -0.3615,  1.2151,  1.4312]]),
 tensor([[-4.9999,  3.9548,  2.2772, -0.7079,  0.4714],
         [-3.9143, -2.6435,  0.5496,  2.8975,  5.0394],
         [-1.0939, -1.0831, -0.3615,  1.2151,  1.4312]]))

In [48]:
x11.mm(x12).mm(x13)

tensor([[ 1.0210, -4.2816, -5.3899],
        [ 9.6202, -0.3951,  0.9506],
        [ 3.5947,  0.4194,  0.1054]])

In [49]:
x11.mm(x12).mm(x13).mm(x11)

tensor([[ 4.1442, -5.3929,  3.4447, 14.4192, -4.8815],
        [-4.3821, 13.8420, 24.0462,  4.0808, -9.5197],
        [-2.1178,  5.2721,  9.1094,  0.4444, -3.2721]])

In [50]:
x14 = torch.randn(3, 4)
v = torch.randn(4)

x14, v

(tensor([[-2.0501,  0.6842, -0.8003, -0.3738],
         [ 1.4904, -1.2968, -0.3243,  0.3105],
         [-0.3423,  0.6976,  1.4117,  2.1331]]),
 tensor([-0.1602,  0.3615,  0.3725, -0.3054]))

In [51]:
 -0.4594 * 0.6623 + -1.1798 * 0.2916 +0.3812 * 0.0409+ -0.0064 *  -1.1908

-0.6250781

In [52]:
torch.mv(x14,v), x14.mv(v)

(tensor([ 0.3919, -0.9233,  0.1815]), tensor([ 0.3919, -0.9233,  0.1815]))

In [53]:
x15 = torch.randn(10,3,4)  # (batch_size,  m, n) : m*n 크기의 행렬을 batch로 처리할 때
x16 = torch.randn(10,4,5)

torch.bmm(x15, x16).size()   
# torch.bmm()에 들어가는 행렬은 (batch_size, l, m)*(batch_size, m, n) 인데, 각 batch마다 (l, m)*(m, n) 행렬곱 연산을 함

torch.Size([10, 3, 5])

In [54]:
torch.bmm(x15, x16)

tensor([[[ 1.7138, -0.4345,  1.1420, -3.3325, -1.2142],
         [-2.0399, -1.2899,  0.7478,  1.4689, -1.2352],
         [-0.3336,  0.5466,  1.0611, -0.8343, -0.3241]],

        [[-1.1467,  1.1880,  1.2328,  0.6938, -1.2643],
         [-2.9654, -5.4339,  2.0389, -1.4294,  0.9106],
         [-1.1729,  1.0340,  0.6531,  0.7732, -2.1821]],

        [[ 0.7773,  0.2123, -0.5464, -0.7696,  1.1562],
         [ 0.2524,  1.9962, -0.8638,  1.9045,  0.0955],
         [-2.2084, -3.0097,  1.8324,  0.0296, -1.2678]],

        [[-0.3516, -2.9943,  2.2078, -1.1990,  1.2413],
         [ 0.3316, -1.1093, -2.3101,  0.6280,  0.4232],
         [ 0.4801,  0.1002,  0.5176, -0.3648,  0.2836]],

        [[ 2.1923,  2.3400, -0.6794,  0.9830,  0.4800],
         [ 2.4723,  1.4585,  2.8229,  2.6509,  0.5795],
         [ 0.4222, -0.1089, -1.4181, -0.7412, -0.7366]],

        [[ 0.7513,  0.2763,  0.5596,  1.1950,  0.4925],
         [-6.9139, -2.2331, -0.4577, -3.1147, -2.8759],
         [ 0.3033, -1.6810,  0.6195, -

In [55]:
x17 = torch.randn(2,2)
x18 = torch.randn(2,2)

torch.dot(x17.view(-1), x18.view(-1)), x17, x18

(tensor(1.6870),
 tensor([[-0.6147,  1.0675],
         [-0.2336,  0.8837]]),
 tensor([[-1.1205,  1.0734],
         [-1.1730, -0.4771]]))

In [56]:
1.7038 *  -0.6295 + -1.6000 *  -1.0304 +  1.4366 * -0.0231 + -0.9917 * 0.1807

0.3637122500000002

In [57]:
torch.dot(x17.view(-1), x18.view(-1))

tensor(1.6870)

In [58]:
x19  = torch.rand(3,4)

x19, x19.t()

(tensor([[0.1185, 0.2355, 0.5599, 0.8966],
         [0.2858, 0.1955, 0.1808, 0.2796],
         [0.3273, 0.3835, 0.2156, 0.6563]]),
 tensor([[0.1185, 0.2858, 0.3273],
         [0.2355, 0.1955, 0.3835],
         [0.5599, 0.1808, 0.2156],
         [0.8966, 0.2796, 0.6563]]))

In [59]:
u, s, v = torch.svd(x19)
u, s, v, x19

(tensor([[-0.7507,  0.6519, -0.1066],
         [-0.3093, -0.4895, -0.8153],
         [-0.5837, -0.5791,  0.5691]]),
 tensor([1.4201, 0.3438, 0.1195]),
 tensor([[-0.2594, -0.7335, -0.4967],
         [-0.3247, -0.4780,  0.2824],
         [-0.4240,  0.4413, -0.7062],
         [-0.8047,  0.1968,  0.4182]]),
 tensor([[0.1185, 0.2355, 0.5599, 0.8966],
         [0.2858, 0.1955, 0.1808, 0.2796],
         [0.3273, 0.3835, 0.2156, 0.6563]]))

In [60]:
torch.dist(x19, torch.mm(torch.mm(u, torch.diag(s)), v.t()))  # torch.dist(a, b, p=2) 에서 a, b의 p-norm

tensor(5.5914e-07)


# Tensor Data Type

In [61]:
x20 = torch.rand(2,2)
x20

tensor([[0.5041, 0.1733],
        [0.2145, 0.6059]])

In [62]:
x20  = torch.LongTensor([1,1])
x20

tensor([1, 1])

In [63]:
x20.float()

tensor([1., 1.])

In [64]:
x20.double()

tensor([1., 1.], dtype=torch.float64)

In [65]:
x20.byte()

tensor([1, 1], dtype=torch.uint8)

In [66]:
x20

tensor([1, 1])

In [67]:
x20 = x20.cpu()
x20

tensor([1, 1])

In [68]:
x20.numpy()

array([1, 1])

In [69]:
torch.from_numpy(np.random.rand(3,2))

tensor([[0.8719, 0.4157],
        [0.6181, 0.3075],
        [0.3291, 0.9245]], dtype=torch.float64)