In [1]:
import torch
from torch.autograd import Variable


# Tensor VS Variable

In [2]:
tensor = torch.rand(2,2,)
x = Variable(tensor, requires_grad=True)

tensor, x

(tensor([[0.9469, 0.3753],
         [0.3080, 0.3845]]),
 tensor([[0.9469, 0.3753],
         [0.3080, 0.3845]], requires_grad=True))

In [3]:
x.sum(), x.sqrt(), x**2, x

(tensor(2.0147, grad_fn=<SumBackward0>),
 tensor([[0.9731, 0.6126],
         [0.5550, 0.6201]], grad_fn=<SqrtBackward>),
 tensor([[0.8966, 0.1408],
         [0.0949, 0.1479]], grad_fn=<PowBackward0>),
 tensor([[0.9469, 0.3753],
         [0.3080, 0.3845]], requires_grad=True))


# Variable

In [4]:
x.data

tensor([[0.9469, 0.3753],
        [0.3080, 0.3845]])

In [5]:
x.requires_grad, x.grad, x.grad_fn  # x.volatile 도 있었으나 없어졌음. 특정 최적화를 못하게 제한하는 변수였음

(True, None, None)

In [6]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)

y = x**3 + 3

z  = Variable(torch.FloatTensor([5]))

x.requires_grad, y.requires_grad, z.requires_grad, y   # 결과를 보면 y결과가 값과 역전파상 첫번째 미분함수를 표시함

(True, True, False, tensor([30.], grad_fn=<AddBackward0>))

In [7]:
y.grad_fn.next_functions[0][0]    # [각 역전파될 함수들][각 함수에서의 값]  ; 깊이 볼 필요는 없음

In [8]:
y.grad_fn.next_functions                                                   # 깊이 볼 필요는 없음

((<PowBackward0 at 0x1f44f352f10>, 0), (None, 0))

In [9]:
y.grad_fn.next_functions[0], y.grad_fn.next_functions[1]                   # 깊이 볼 필요는 없음

((<PowBackward0 at 0x1f44f352f10>, 0), (None, 0))

In [10]:
y.grad_fn.next_functions[0][0], y.grad_fn.next_functions[0][1]             # 깊이 볼 필요는 없음

(<PowBackward0 at 0x1f44f352f10>, 0)

In [11]:
y.grad_fn.next_functions[1][0], y.grad_fn.next_functions[1][1]             # 깊이 볼 필요는 없음

(None, 0)

In [12]:
y.grad_fn.next_functions[0][0].next_functions[0][0]                        # 깊이 볼 필요는 없음. 더 내려가면 오류

In [13]:
y.backward()

In [14]:
x, x.grad

(tensor([3.], requires_grad=True), tensor([27.]))

In [15]:
x.grad.data.zero_(), x.grad                    # x=0에서의 기울기

(tensor([0.]), tensor([0.]))

In [16]:
x1 = Variable(torch.ones(2), requires_grad = True)
x2 = Variable(torch.ones(2))

In [17]:
y = x1 * 2 + x2
y

tensor([3., 3.], grad_fn=<AddBackward0>)

In [18]:
y.backward(torch.Tensor([1,1]))

In [19]:
x1.grad

tensor([2., 2.])

In [20]:
x2.grad

In [21]:
x1.grad.data.zero_()

tensor([0., 0.])