In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit
import sklearn
import tensorflow as tf

In [3]:
nd1=np.array([1,2,3,4])
nd1

array([1, 2, 3, 4])

In [5]:
nd2=np.array([[1,2,3],[4,5,6]]) #2차원 (평면)으로 나타내야기에 [[]]로 씀.
nd2


array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
nd2.ndim #number of dimension

2

In [6]:
type(nd2)

numpy.ndarray

In [7]:
nd1.ndim

1

In [8]:
type(nd1)

numpy.ndarray

In [10]:
nd1.size

4

In [11]:
nd2.size

6

In [12]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
a=np.ones((3,4))

In [16]:
a.size

12

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
np.arange(12).reshape(4,-1)#크기를 알아서 계산 해 줌

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.arange(1200).reshape(3,400)

array([[   0,    1,    2, ...,  397,  398,  399],
       [ 400,  401,  402, ...,  797,  798,  799],
       [ 800,  801,  802, ..., 1197, 1198, 1199]])

In [27]:
from urllib import request
from bs4 import BeautifulSoup

target = request.urlopen("http://www.kma.go.kr/weather/forecast/mid-term-rss3.jsp?stnId=108")

soup = BeautifulSoup(target, "html.parser")

for location in soup.select("location"):
    print("도시:", location.select_one("city").string)
    print("날씨:", location.select_one("wf").string)
    print("최저기온:", location.select_one("tmn").string)
    print("최고기온:", location.select_one("tmx").string)
    print()


도시: 서울
날씨: 맑음
최저기온: 5
최고기온: 16

도시: 인천
날씨: 맑음
최저기온: 6
최고기온: 15

도시: 수원
날씨: 맑음
최저기온: 4
최고기온: 16

도시: 파주
날씨: 맑음
최저기온: 0
최고기온: 16

도시: 이천
날씨: 맑음
최저기온: 2
최고기온: 17

도시: 평택
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 춘천
날씨: 맑음
최저기온: 2
최고기온: 17

도시: 원주
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 강릉
날씨: 맑음
최저기온: 5
최고기온: 13

도시: 대전
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 세종
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 홍성
날씨: 맑음
최저기온: 2
최고기온: 16

도시: 청주
날씨: 맑음
최저기온: 5
최고기온: 17

도시: 충주
날씨: 맑음
최저기온: 2
최고기온: 16

도시: 영동
날씨: 맑음
최저기온: 1
최고기온: 17

도시: 광주
날씨: 맑음
최저기온: 5
최고기온: 18

도시: 목포
날씨: 맑음
최저기온: 7
최고기온: 15

도시: 여수
날씨: 맑음
최저기온: 8
최고기온: 15

도시: 순천
날씨: 맑음
최저기온: 6
최고기온: 17

도시: 광양
날씨: 맑음
최저기온: 6
최고기온: 17

도시: 나주
날씨: 맑음
최저기온: 2
최고기온: 18

도시: 전주
날씨: 맑음
최저기온: 4
최고기온: 17

도시: 군산
날씨: 맑음
최저기온: 3
최고기온: 15

도시: 정읍
날씨: 맑음
최저기온: 3
최고기온: 17

도시: 남원
날씨: 맑음
최저기온: 2
최고기온: 18

도시: 고창
날씨: 맑음
최저기온: 3
최고기온: 16

도시: 무주
날씨: 맑음
최저기온: 1
최고기온: 16

도시: 부산
날씨: 맑음
최저기온: 8
최고기온: 16

도시: 울산
날씨: 맑음
최저기온: 7
최고기온: 14

도시: 창원
날씨: 맑음
최저기온: 7
최고기온: 17

도시: 진주
날씨: 맑음
최저기온: 4
최고기온: 17

도시: 거창
날

In [28]:
from flask import Flask

app = Flask(__name__)

@app.route("/")
def hello():
    return "<h1> Hello, </h1>"

In [ ]:
from math import *  #math에 있는 모든 기능들 다 가져 옴